# Use root/example as user/password credentials
version: '3.7'

services:
  rabbit-mq:
    image: rabbitmq:3.8.1-alpine
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
      
  sql.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - cqrs-microservices-sql-data:/data

  redis:
    image: redis
    container_name: readcache
    ports:
      - 6379:6379

volumes:
    cqrs-microservices-sql-data: